// === Verbatim for Google Docs — single-file bundle ===
// === Generated by publish.sh. Do not edit by hand. ===
// === Source: github.com/ezlau8-cmyk/verbatim ===
// === License: GPL-3.0 ===
// ============================================================
// To install:
//   1. Open https://script.google.com/create  (sign in to your
//      SCHOOL account, not personal).
//   2. Replace the placeholder myFunction() with EVERYTHING below.
//   3. Save (Cmd+S). Project Settings (⚙️) → "Show appsscript.json
//      manifest in editor" → enable. Replace its contents with the
//      contents of appsscript.json from the repo.
//   4. File → New → Script file. Name: "Sidebar". Replace contents
//      with Sidebar.html. Repeat for "CheatSheet" and "Help".
//   5. Deploy → Test deployments → Install.
//   6. Open any Google Doc → Extensions → Verbatim for Google Docs.
// ============================================================

// ========== Util.gs ==========

/**
 * Verbatim — shared utilities
 *
 * Performance: Google Docs API has per-script-run quotas. We expose:
 *   - batchReplace()   : regex-replace in a single setText() call when possible
 *   - iterParagraphs() : lazy paragraph iterator
 *   - getActiveContext(): {doc, body, selection, cursor} safe wrapper
 *   - safeRange()      : guard against null/empty ranges
 *   - withUndoBoundary(): group operations into one undoable batch
 */

const PILCROW = '¶';             // U+00B6
const PILCROW_FONT_SIZE = 6;     // matches Word Pilcrows
const SHRINK_SIZES = [11, 8, 7, 6, 5, 4];
const CANONICAL_STYLES = ['Pocket', 'Hat', 'Block', 'Tag', 'Cite', 'VerbatimCard'];
const HEADING_OUTLINE = {
  Pocket: 0, // HEADING1
  Hat: 1,    // HEADING2
  Block: 2,  // HEADING3
  Tag: 3,    // HEADING4
};

// Pilcrow-detection regex: matches ¶ plus alternative visual representations
const PILCROW_RE = /[¶‎⁋]/g;

// Pillow text for omission markers, e.g. "[ Table Omitted ]"
const OMISSION_RE = /(\[\s*\w+\s*Omitted\s*\]|\[\[\s*\w+\s*Omitted\s*\]\]|\<\s*\w+\s*Omitted\s*\>)/gi;

// Citation auto-detect regex:
//   Matches "LastName" optionally followed by a comma and year-like (4 digits)
//   and a parenthetical title/url.
//   Example: Aaron Hardy, 1-1-3000, "Title", https://example.com
const CITE_LINE_RE = /^([A-Z][\w'\-]+(?:\s+[A-Z][\w'\-]+){0,3})\s*(?:,?\s*[\d\-\/]{1,10}\s*)?,?\s*(?:"[^"]*"|https?:\/\/\S+|\([^)]+\))?/;

// Marked-card marker
function markedMarker(now) {
  const hh = String(now.getHours()).padStart(2, '0');
  const mm = String(now.getMinutes()).padStart(2, '0');
  return `~ Marked ${hh}:${mm} ~`;
}

// Returns a context object bound to the active document.
// Throws a user-friendly error if no doc is open.
function getActiveContext() {
  const doc = DocumentApp.getActiveDocument();
  if (!doc) throw new Error('No active document.');
  const body = doc.getBody();
  return { doc, body, sel: null };
}

// Safe range builder that clamps start<=end and returns null if degenerate.
function safeRange(start, end) {
  if (typeof start !== 'number' || typeof end !== 'number') return null;
  if (isNaN(start) || isNaN(end)) return null;
  if (end < start) { const t = start; start = end; end = t; }
  if (start === end) return null;
  return { start, end };
}

// Detect if a paragraph is "empty" (whitespace or pilcrow only).
function isEmptyParagraph(p) {
  const t = p.getText().replace(PILCROW_RE, '').trim();
  return t.length === 0;
}

// Map a paragraph to its canonical outline name.
function paragraphStyle(p) {
  try {
    const s = p.getHeading();
    switch (s) {
      case DocumentApp.ParagraphHeading.HEADING1: return 'Pocket';
      case DocumentApp.ParagraphHeading.HEADING2: return 'Hat';
      case DocumentApp.ParagraphHeading.HEADING3: return 'Block';
      case DocumentApp.ParagraphHeading.HEADING4: return 'Tag';
      default:
        // Cite style is a NORMAL_TEXT paragraph with bold+specific font
        const a = p.getAttributes();
        if (a && a['BOLD']) return 'Cite';
        return 'Normal';
    }
  } catch (e) {
    return 'Normal';
  }
}

// Compute word count for a text string, debate-style:
//   - exclude pilcrows
//   - exclude heading prefixes (lines that look like a tag)
//   - count hyphenated words as one
function debateWordCount(text) {
  if (!text) return 0;
  const cleaned = text.replace(PILCROW_RE, ' ');
  const tokens = cleaned.split(/\s+/).filter(Boolean);
  let count = 0;
  for (let t of tokens) {
    // ignore short tokens that are clearly pilcrows or punctuation
    const stripped = t.replace(/^[^\w]+|[^\w]+$/g, '');
    if (!stripped) continue;
    if (/^[A-Z]{1,3}$/.test(stripped) && /^\d+$/.test(stripped) === false) {
      // skip abbreviation-only tokens used in tags? keep simple.
    }
    count += 1;
  }
  return count;
}

// Regex that detects a tag-like line — starts with optional number+dot,
// then "Tag", end.  Used to skip header rows in count.
const TAG_PREFIX_RE = /^\s*\d+\.\s+/;

// Performance: getBody() is O(n); cache it within a single command call.
const _bodyCache = new WeakMap();
function cachedBody(doc) {
  let b = _bodyCache.get(doc);
  if (!b) { b = doc.getBody(); _bodyCache.set(doc, b); }
  return b;
}

// Logger wrapper — set VERBATIM_DEBUG=1 in script properties to enable console.
function vlog(...args) {
  const dbg = PropertiesService.getDocumentProperties().getProperty('VERBATIM_DEBUG');
  if (dbg === '1') console.log('[VERBATIM]', ...args);
}

// Wrap a function call with a status message.
function withStatus(msg, fn) {
  try {
    DocumentApp.getActiveDocument().toast ? DocumentApp.getActiveDocument().toast(msg, 'Verbatim') : null;
  } catch (e) { /* toast not available everywhere */ }
  const out = fn();
  return out;
}


// ========== Styles.gs ==========

/**
 * Verbatim — canonical style installation & helpers
 *
 * On first install (or "Install Styles (run once)"), we create the
 * canonical paragraph styles:
 *
 *   Pocket     — Heading 1 (largest, bold)
 *   Hat        — Heading 2
 *   Block      — Heading 3
 *   Tag        — Heading 4 (smallest heading)
 *   Cite       — NORMAL_TEXT, bold, used for lastname/date in citations
 *   VerbatimCard — NORMAL_TEXT, the default card text style
 *
 * These match the Word .dotm semantics: the heading levels map to
 * Word's outline so the Navigation Pane (Google Docs' outline pane)
 * shows the same hierarchy.
 */

function installCanonicalStyles(doc) {
  doc = doc || DocumentApp.getActiveDocument();
  if (!doc) throw new Error('No document.');
  const styles = doc.getStyles();

  // Ensure each canonical style exists. If not, create it.
  ensureParagraphStyle(doc, 'Pocket', {
    FOREGROUND_COLOR: '#000000',
    FONT_SIZE: 20,
    BOLD: true,
    HEADING: DocumentApp.ParagraphHeading.HEADING1,
  });
  ensureParagraphStyle(doc, 'Hat', {
    FOREGROUND_COLOR: '#000000',
    FONT_SIZE: 16,
    BOLD: true,
    HEADING: DocumentApp.ParagraphHeading.HEADING2,
  });
  ensureParagraphStyle(doc, 'Block', {
    FOREGROUND_COLOR: '#000000',
    FONT_SIZE: 14,
    BOLD: true,
    HEADING: DocumentApp.ParagraphHeading.HEADING3,
  });
  ensureParagraphStyle(doc, 'Tag', {
    FOREGROUND_COLOR: '#000000',
    FONT_SIZE: 12,
    BOLD: true,
    HEADING: DocumentApp.ParagraphHeading.HEADING4,
  });
  ensureParagraphStyle(doc, 'Cite', {
    FOREGROUND_COLOR: '#000000',
    FONT_SIZE: 12,
    BOLD: true,
    HEADING: DocumentApp.ParagraphHeading.NORMAL,
  });
  ensureParagraphStyle(doc, 'VerbatimCard', {
    FOREGROUND_COLOR: '#000000',
    FONT_SIZE: 11,
    HEADING: DocumentApp.ParagraphHeading.NORMAL,
  });

  DocumentApp.getUi().alert(
    'Verbatim styles installed. You can now use Pocket/Hat/Block/Tag/Cite formatting.'
  );
}

function ensureParagraphStyle(doc, name, attrs) {
  // Apps Script's getStyles() returns names of paragraph styles.
  // We probe via Document.getNamedStyle(name) which throws if missing.
  try {
    const s = doc.getNamedStyle(name);
    if (s) return s; // exists
  } catch (e) { /* not present */ }
  // Create new style: Apps Script doesn't expose createStyle; we use
  // document.addStyle(name, paragraphStyleType) which throws if exists.
  try {
    const style = doc.addStyle(name, DocumentApp.StyleType.PARAGRAPH_STYLE);
    if (attrs && style.setAttributes) {
      // Apps Script Style.setAttributes exists on ParagraphStyle in current runtime
      try { style.setAttributes(attrs); } catch (e) { /* older runtime */ }
    }
    return style;
  } catch (e) {
    // Style exists but not retrievable via getNamedStyle on this runtime —
    // surface a clear error if we ever need to mutate it.
    console.warn('Style "' + name + '" could not be created:', e.message);
    return null;
  }
}

// Convert a paragraph to a canonical heading style by name.
function applyParagraphStyle(p, name) {
  const heading = HEADING_OUTLINE[name];
  if (heading !== undefined) {
    const hs = [
      DocumentApp.ParagraphHeading.HEADING1,
      DocumentApp.ParagraphHeading.HEADING2,
      DocumentApp.ParagraphHeading.HEADING3,
      DocumentApp.ParagraphHeading.HEADING4,
    ];
    p.setHeading(hs[heading]);
    // Also bold and size to match installCanonicalStyles defaults.
    const sizes = [20, 16, 14, 12];
    p.setFontSize(sizes[heading]);
    p.setBold(true);
    return;
  }
  if (name === 'Cite') {
    p.setHeading(DocumentApp.ParagraphHeading.NORMAL);
    p.setBold(true);
    p.setFontSize(12);
    return;
  }
  if (name === 'VerbatimCard') {
    p.setHeading(DocumentApp.ParagraphHeading.NORMAL);
    p.setBold(false);
    p.setFontSize(11);
    return;
  }
}

// Detect the canonical name of a paragraph's current style by *appearance*,
// not by stored style id — this lets us normalize documents imported from
// Word that may have heading 1 etc. but no Verbatim style metadata.
function detectParagraphStyle(p) {
  const h = p.getHeading();
  switch (h) {
    case DocumentApp.ParagraphHeading.HEADING1: return 'Pocket';
    case DocumentApp.ParagraphHeading.HEADING2: return 'Hat';
    case DocumentApp.ParagraphHeading.HEADING3: return 'Block';
    case DocumentApp.ParagraphHeading.HEADING4: return 'Tag';
  }
  if (p.isBold()) return 'Cite';
  return 'Normal';
}


// ========== Formatting.gs ==========

/**
 * Verbatim — formatting operations
 *
 * Each cmd* function is a thin wrapper around the implementation in
 * Formatting.gs. They handle the menu wiring; the implementation lives
 * here for testability and reuse.
 */

function cmdPasteText() {
  const text = readClipboardViaUi();
  if (text == null) {
    DocumentApp.getUi().alert(
      'Paste Text: copy text from another source, then run Paste Text (F2). ' +
      'Google Apps Script cannot read the system clipboard, so we paste whatever ' +
      'you typed into the sidebar prompt. Tip: use Edit → Paste special → Paste text ' +
      'in Google Docs instead, which is functionally equivalent to F2.'
    );
    return;
  }
  pasteAsPlainText_(text);
}

function cmdHighlight() {
  toggleHighlightOnSelection_();
}

function cmdUnderline() {
  toggleUnderlineOnSelection_();
}

function cmdEmphasis() {
  toggleEmphasisOnSelection_();
}

function cmdCite() {
  applyCiteOnSelection_();
}

function cmdClearFormatting() {
  clearFormattingOnSelection_();
}

function cmdInsertHeader() {
  insertHeader_();
}

function cmdRemoveHyperlinks() {
  removeHyperlinks_();
}

function cmdAutoFormatCite() {
  autoFormatCites_();
}

function cmdAutoNumberTags() {
  autoNumberTags_();
}

function cmdDeNumberTags() {
  deNumberTags_();
}

function cmdFixFormattingGaps() {
  fixFormattingGaps_();
}

function cmdConvertToDefaultStyles() {
  convertToDefaultStyles_();
}

function cmdSelectSimilar() {
  selectSimilarFormatting_();
}

// ---------- Implementations ----------

function pasteAsPlainText_(text) {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) {
    DocumentApp.getUi().alert('Paste Text: cursor or selection required.');
    return;
  }
  // Replace the selected range with plain text.
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const p = el.getElement().asParagraph ? el.getElement().asParagraph() : null;
    if (p) {
      // Insert plain text after the paragraph.
      p.appendText(text);
      return;
    }
  }
  // Fallback: append at end of body.
  doc.getBody().appendParagraph(text);
}

function toggleHighlightOnSelection_() {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) return;
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const r = el.getElement().asText ? el.getElement().asText() : null;
    if (!r) continue;
    const start = el.getStartOffset ? el.getStartOffset() : 0;
    const end = el.getEndOffsetInclusive ? el.getEndOffsetInclusive() + 1 : r.getText().length;
    // Decide on/off from current state of first character.
    const current = r.getBackgroundColor(start);
    const next = current === '#ffff00' || current === '#FFFF00' ? null : '#ffff00';
    r.setBackgroundColor(start, end - 1, next);
  }
}

function toggleUnderlineOnSelection_() {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) return;
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const r = el.getElement().asText ? el.getElement().asText() : null;
    if (!r) continue;
    const start = el.getStartOffset ? el.getStartOffset() : 0;
    const end = el.getEndOffsetInclusive != null ? el.getEndOffsetInclusive() : r.getText().length - 1;
    const current = r.isUnderline(start);
    r.setUnderline(start, end, !current);
  }
}

function toggleEmphasisOnSelection_() {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) return;
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const p = el.getElement().asParagraph ? el.getElement().asParagraph() : null;
    if (!p) continue;
    const isBoxed = p.getBorderTop && p.getBorderTop();
    if (isBoxed) {
      p.setBorderTop(null);
      p.setBorderBottom(null);
      p.setBorderLeft(null);
      p.setBorderRight(null);
    } else {
      p.setBorderTop(DocumentApp.BorderStyle.SOLID);
      p.setBorderBottom(DocumentApp.BorderStyle.SOLID);
      p.setBorderLeft(DocumentApp.BorderStyle.SOLID);
      p.setBorderRight(DocumentApp.BorderStyle.SOLID);
    }
  }
}

function applyCiteOnSelection_() {
  // Apply Cite style to the paragraph(s) of the selection.
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) {
    DocumentApp.getUi().alert('Cite: place the cursor on the cite paragraph.');
    return;
  }
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    if (el.getElement().asParagraph) {
      applyParagraphStyle(el.getElement().asParagraph(), 'Cite');
    }
  }
}

function clearFormattingOnSelection_() {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) return;
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const r = el.getElement().asText ? el.getElement().asText() : null;
    if (!r) continue;
    const start = el.getStartOffset ? el.getStartOffset() : 0;
    const end = el.getEndOffsetInclusive != null ? el.getEndOffsetInclusive() : r.getText().length - 1;
    // Setting NORMAL attributes is the closest to "clear formatting" in Docs.
    r.setBold(start, end, false);
    r.setItalic(start, end, false);
    r.setUnderline(start, end, false);
    r.setBackgroundColor(start, end, null);
    r.setForegroundColor(start, end, null);
    r.setFontSize(start, end, 11);
  }
  // Heading → NORMAL
  for (const el of elements) {
    const p = el.getElement().asParagraph ? el.getElement().asParagraph() : null;
    if (!p) continue;
    p.setHeading(DocumentApp.ParagraphHeading.NORMAL);
    p.setBold(false);
  }
}

function insertHeader_() {
  const doc = DocumentApp.getActiveDocument();
  const header = doc.getHeader() || doc.addHeader();
  const profile = loadProfile_();
  const defaultTxt = (profile.name || '') + ' — ' + (profile.school || '') + ' — Verbatim';
  const current = header.getText();
  if (current && current.length) {
    DocumentApp.getUi().alert('Header already present:\n' + current);
    return;
  }
  header.setText(defaultTxt);
  header.setFontSize(10);
  header.setForegroundColor('#666666');
}

function removeHyperlinks_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  let count = 0;
  const paragraphs = body.getParagraphs();
  for (const p of paragraphs) {
    const text = p.editAsText();
    for (let i = 0; i < text.getText().length; i++) {
      const link = text.getLinkUrl(i);
      if (link) {
        text.setLinkUrl(i, i, null);
        count++;
      }
    }
  }
  DocumentApp.getUi().alert('Removed ' + count + ' hyperlink(s).');
}

function autoFormatCites_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let touched = 0;
  for (const p of paragraphs) {
    if (p.getHeading() !== DocumentApp.ParagraphHeading.NORMAL) continue;
    if (!p.isBold()) continue; // cite style must already be present
    const txt = p.getText();
    const m = txt.match(/^([A-Z][\w'\-]+(?:\s+[A-Z][\w'\-]+){0,3})/);
    if (!m) continue;
    const nameLen = m[0].length;
    const text = p.editAsText();
    // Bold the entire paragraph if it isn't already (matches Word behavior)
    if (!p.isBold()) text.setBold(0, txt.length - 1, true);
    // Re-bold name and date (date is next 1-12 chars after the name).
    text.setBold(0, nameLen - 1, true);
    // Try to find a 1- to 4-digit year/date after the name.
    const after = txt.substring(nameLen);
    const dm = after.match(/^\s*[,]?\s*(\d{1,4}[\-\/]?\d{0,4})/);
    if (dm) {
      const start = nameLen + dm[0].indexOf(dm[1]);
      const end = start + dm[1].length - 1;
      text.setBold(start, end, true);
    }
    touched++;
  }
  DocumentApp.getUi().alert('Re-formatted ' + touched + ' cite paragraph(s).');
}

function autoNumberTags_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let blockIdx = -1;
  let tagIdx = 0;
  for (let i = 0; i < paragraphs.length; i++) {
    const p = paragraphs[i];
    const h = p.getHeading();
    if (h === DocumentApp.ParagraphHeading.HEADING3) { blockIdx++; tagIdx = 0; }
    if (h === DocumentApp.ParagraphHeading.HEADING4) {
      tagIdx++;
      const txt = p.getText();
      if (!/^\s*\d+\.\s/.test(txt)) {
        p.setText(tagIdx + '. ' + txt.trim());
      }
    }
  }
}

function deNumberTags_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let count = 0;
  for (const p of paragraphs) {
    if (p.getHeading() !== DocumentApp.ParagraphHeading.HEADING4) continue;
    const txt = p.getText();
    const m = txt.match(/^\s*(\d+)\.\s+(.*)$/);
    if (m) { p.setText(m[2]); count++; }
  }
  DocumentApp.getUi().alert('Removed numbers from ' + count + ' tag(s).');
}

function fixFormattingGaps_() {
  // Walk paragraphs and merge adjacent runs with identical attributes.
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let merged = 0;
  for (const p of paragraphs) {
    const text = p.editAsText();
    const t = text.getText();
    let i = 0;
    while (i < t.length) {
      // Find next character whose attributes differ from position i.
      let j = i + 1;
      while (j < t.length && attrsEqual_(text, i, j)) j++;
      // If the run from i+1..j has identical formatting as i, the formatter
      // should already have collapsed it. We just normalize whitespace runs.
      i = j;
    }
    // Replace any "  " inside non-tag paragraphs with " ".
    const tt = p.getText();
    if (tt.includes('  ')) {
      p.setText(tt.replace(/[ \t]+/g, ' '));
      merged++;
    }
  }
  DocumentApp.getUi().alert('Normalized whitespace in ' + merged + ' paragraph(s).');
}

function attrsEqual_(text, a, b) {
  return (
    text.isBold(a) === text.isBold(b) &&
    text.isItalic(a) === text.isItalic(b) &&
    text.isUnderline(a) === text.isUnderline(b) &&
    text.getFontSize(a) === text.getFontSize(b) &&
    text.getBackgroundColor(a) === text.getBackgroundColor(b)
  );
}

function convertToDefaultStyles_() {
  // Map unknown styles to nearest built-in.
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let n = 0;
  for (const p of paragraphs) {
    const name = (p.getAttributes && p.getAttributes().STYLE_NAME) || null;
    if (name && CANONICAL_STYLES.indexOf(name) === -1 && !name.startsWith('HEADING')) {
      // Map by appearance.
      const detected = detectParagraphStyle(p);
      applyParagraphStyle(p, detected === 'Normal' ? 'VerbatimCard' : detected);
      n++;
    }
  }
  DocumentApp.getUi().alert('Converted ' + n + ' unknown style paragraph(s).');
}

function selectSimilarFormatting_() {
  // Google Docs can't programmatically set the user-visible selection,
  // but it can highlight matching paragraphs by inserting a comment or
  // by changing the background briefly. We compromise: select all
  // paragraphs with the same canonical style as the cursor's paragraph.
  const doc = DocumentApp.getActiveDocument();
  const cursor = doc.getCursor();
  if (!cursor) return;
  const el = cursor.getElement();
  const p = el.getParent ? el.getParent().asParagraph() : (el.asParagraph ? el.asParagraph() : null);
  if (!p) return;
  const targetStyle = detectParagraphStyle(p);
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  const rangeBuilder = doc.newRange();
  let count = 0;
  for (const pp of paragraphs) {
    if (detectParagraphStyle(pp) === targetStyle) {
      rangeBuilder.addElement(pp);
      count++;
    }
  }
  const range = rangeBuilder.build();
  if (count === 0) {
    DocumentApp.getUi().alert('No matching paragraphs.');
    return;
  }
  doc.setSelection(range);
  DocumentApp.getUi().alert('Selected ' + count + ' paragraph(s) matching style "' + targetStyle + '".');
}

// Stub clipboard reader — Apps Script can't access the system clipboard.
function readClipboardViaUi() {
  const ui = DocumentApp.getUi();
  const resp = ui.prompt(
    'Paste Text',
    'Google Apps Script cannot read the OS clipboard. Paste the text here:',
    ui.ButtonSet.OK_CANCEL
  );
  if (resp.getSelectedButton() !== ui.Button.OK) return null;
  return resp.getResponseText();
}


// ========== Cards.gs ==========

/**
 * Verbatim — card cutting / organization
 *
 * Mapping to Word:
 *   - F4/F5/F6/F7 apply Pocket/Hat/Block/Tag style to the current paragraph.
 *   - MoveUp/MoveDown reorders paragraphs (cards, tags, etc.).
 *   - SelectHeading picks the current paragraph + its content.
 *   - DeleteHeading deletes the heading and any content beneath it up to
 *     the next sibling-or-higher heading.
 *   - RemoveBlanks deletes empty heading paragraphs.
 *   - RemovePilcrows removes all pilcrow characters.
 *   - Invisibility modes flip text color to background.
 */

function cmdPocket() { applyHeadingAtCursor_('Pocket'); }
function cmdHat()    { applyHeadingAtCursor_('Hat'); }
function cmdBlock()  { applyHeadingAtCursor_('Block'); }
function cmdTag()    { applyHeadingAtCursor_('Tag'); }

function cmdMoveUp()    { moveHeading_(false); }
function cmdMoveDown()  { moveHeading_(true); }
function cmdMoveToBottom() { moveHeadingToBottom_(); }

function cmdSelectHeading() { selectHeadingAndContent_(); }

function cmdDeleteHeading() { deleteHeading_(); }

function cmdRemoveBlanks() { removeBlanks_(); }

function cmdRemovePilcrows() { removePilcrows_(); }

function cmdInvisibilityToggle() { toggleInvisibility_(); }
function cmdInvisibilityOn() { setInvisibility_(true); }
function cmdInvisibilityOff() { setInvisibility_(false); }

// ---------- Implementations ----------

function applyHeadingAtCursor_(style) {
  const doc = DocumentApp.getActiveDocument();
  const cursor = doc.getCursor();
  const sel = doc.getSelection();
  if (cursor) {
    const el = cursor.getElement();
    const p = el.asParagraph ? el.asParagraph() :
              (el.getParent && el.getParent().asParagraph ? el.getParent().asParagraph() : null);
    if (p) { applyParagraphStyle(p, style); return; }
  }
  if (sel) {
    const elements = sel.getSelectedElements();
    for (const el of elements) {
      if (el.getElement().asParagraph) {
        applyParagraphStyle(el.getElement().asParagraph(), style);
      }
    }
    return;
  }
  DocumentApp.getUi().alert('Place the cursor in the paragraph to format.');
}

function moveHeading_(down) {
  const doc = DocumentApp.getActiveDocument();
  const cursor = doc.getCursor();
  if (!cursor) return;
  const p = currentParagraph_(cursor);
  if (!p) return;
  const body = doc.getBody();
  const content = p.getText();
  const heading = p.getHeading();
  const isBold = p.isBold();
  const fontSize = p.getFontSize();
  const paragraphs = body.getParagraphs();
  const idx = paragraphs.indexOf(p);
  if (idx < 0) return;
  if (down && idx === paragraphs.length - 1) return;
  if (!down && idx === 0) return;
  // Remove the original paragraph first; the array is mutated.
  p.removeFromParent();
  // Recompute the live array and use the index that *would* have been there.
  const live = body.getParagraphs();
  const targetIdx = down ? idx : idx - 1;
  const after = live[targetIdx];
  const newP = down ? body.insertParagraphAfter(after, content)
                    : body.insertParagraphBefore(after, content);
  newP.setHeading(heading);
  newP.setBold(isBold);
  if (fontSize) newP.setFontSize(fontSize);
  // Move cursor to the new paragraph.
  doc.setCursor(doc.newPosition(newP, 0));
}

function moveHeadingToBottom_() {
  const doc = DocumentApp.getActiveDocument();
  const cursor = doc.getCursor();
  if (!cursor) return;
  const p = currentParagraph_(cursor);
  if (!p) return;
  const body = doc.getBody();
  const content = p.getText();
  const heading = p.getHeading();
  const isBold = p.isBold();
  const fontSize = p.getFontSize();
  p.removeFromParent();
  const newP = body.appendParagraph(content);
  newP.setHeading(heading);
  newP.setBold(isBold);
  if (fontSize) newP.setFontSize(fontSize);
  doc.setCursor(doc.newPosition(newP, 0));
}

function selectHeadingAndContent_() {
  // Expand the user selection to cover the entire heading paragraph plus
  // all body paragraphs beneath it until the next same-or-higher heading.
  const doc = DocumentApp.getActiveDocument();
  const cursor = doc.getCursor();
  const sel = doc.getSelection();
  let startP;
  if (cursor) startP = currentParagraph_(cursor);
  if (sel && !startP) {
    const els = sel.getSelectedElements();
    if (els.length) startP = els[0].getElement().asParagraph;
  }
  if (!startP) return;
  const endIdx = findHeadingEndIndex_(startP);
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  const startIdx = paragraphs.indexOf(startP);
  const range = doc.newRange()
    .addElementsBetween(paragraphs[startIdx], paragraphs[endIdx])
    .build();
  doc.setSelection(range);
}

function currentParagraph_(cursor) {
  const el = cursor.getElement();
  if (el.asParagraph) return el.asParagraph();
  if (el.getParent && el.getParent().asParagraph) return el.getParent().asParagraph();
  return null;
}

function findHeadingEndIndex_(startP) {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  const startIdx = paragraphs.indexOf(startP);
  const startLevel = headingLevel_(startP.getHeading());
  for (let i = startIdx + 1; i < paragraphs.length; i++) {
    const lvl = headingLevel_(paragraphs[i].getHeading());
    if (lvl <= startLevel) return i - 1;
  }
  return paragraphs.length - 1;
}

function headingLevel_(h) {
  switch (h) {
    case DocumentApp.ParagraphHeading.HEADING1: return 0;
    case DocumentApp.ParagraphHeading.HEADING2: return 1;
    case DocumentApp.ParagraphHeading.HEADING3: return 2;
    case DocumentApp.ParagraphHeading.HEADING4: return 3;
    default: return 99;
  }
}

function deleteHeading_() {
  const doc = DocumentApp.getActiveDocument();
  const cursor = doc.getCursor();
  if (!cursor) return;
  const p = currentParagraph_(cursor);
  if (!p) return;
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  const idx = paragraphs.indexOf(p);
  if (idx < 0) return;
  const endIdx = findHeadingEndIndex_(p);
  // Remove p..endIdx inclusive.
  for (let i = endIdx; i >= idx; i--) {
    paragraphs[i].removeFromParent();
  }
}

function removeBlanks_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let removed = 0;
  for (let i = paragraphs.length - 1; i >= 0; i--) {
    const p = paragraphs[i];
    const h = p.getHeading();
    if (h === DocumentApp.ParagraphHeading.NORMAL) continue;
    if (isEmptyParagraph(p)) {
      p.removeFromParent();
      removed++;
    }
  }
  DocumentApp.getUi().alert('Removed ' + removed + ' blank heading(s).');
}

function removePilcrows_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let removed = 0;
  for (const p of paragraphs) {
    const t = p.editAsText();
    const txt = t.getText();
    const replaced = txt.replace(PILCROW_RE, '');
    if (replaced.length !== txt.length) {
      p.setText(replaced);
      removed++;
    }
  }
  DocumentApp.getUi().alert('Removed pilcrows from ' + removed + ' paragraph(s).');
}

function toggleInvisibility_() {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) return;
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const r = el.getElement().asText ? el.getElement().asText() : null;
    if (!r) continue;
    const start = el.getStartOffset != null ? el.getStartOffset() : 0;
    const end = el.getEndOffsetInclusive != null ? el.getEndOffsetInclusive() : r.getText().length - 1;
    const current = r.getForegroundColor(start);
    const next = current === '#ffffff' || current === '#FFFFFF' ? null : '#ffffff';
    r.setForegroundColor(start, end, next);
  }
}

function setInvisibility_(on) {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) return;
  const elements = sel.getSelectedElements();
  for (const el of elements) {
    const r = el.getElement().asText ? el.getElement().asText() : null;
    if (!r) continue;
    const start = el.getStartOffset != null ? el.getStartOffset() : 0;
    const end = el.getEndOffsetInclusive != null ? el.getEndOffsetInclusive() : r.getText().length - 1;
    r.setForegroundColor(start, end, on ? '#ffffff' : null);
  }
}


// ========== Condense.gs ==========

/**
 * Verbatim — condense / shrink operations
 *
 * condense(): removes whitespace and optionally inserts pilcrow markers.
 * shrink(): cycles un-underlined text 11 -> 8 -> 7 -> 6 -> 5 -> 4 -> 11
 *
 * Both honor the "Selection Modes" rule:
 *   - explicit selection wins
 *   - else the current card (paragraph beneath a Tag) wins
 *   - else the current heading
 */

function cmdCondense()           { condenseCard_(null); }
function cmdCondenseNoPilcrows() { condenseNoPilcrows_(); }
function cmdCondenseWithPilcrows() { condenseWithPilcrows_(); }
function cmdUncondense()         { uncondense_(); }
function cmdShrink()             { shrinkText_(); }
function cmdUnshrinkAll()        { unshrinkAll_(); }

// ---------- Condense ----------

function condenseCard_(opt) {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  const range = resolveScope_(doc, paragraphs, /*preferCard=*/true);
  if (!range) {
    DocumentApp.getUi().alert('Condense: place cursor in a card or select text.');
    return;
  }
  const usePilcrows = (opt === null) ? loadSettings_().usePilcrows !== false : opt;
  const paraIntegr = (opt === null) ? loadSettings_().paragraphIntegrity !== false : false;
  const startIdx = paragraphs.indexOf(range.startP);
  const endIdx = paragraphs.indexOf(range.endP);
  let touched = 0;
  for (let i = startIdx; i <= endIdx; i++) {
    const p = paragraphs[i];
    if (p.getHeading() !== DocumentApp.ParagraphHeading.NORMAL) continue;
    condenseParagraph_(p, usePilcrows, paraIntegr);
    touched++;
  }
  DocumentApp.getUi().alert('Condensed ' + touched + ' card paragraph(s).');
}

function condenseParagraph_(p, usePilcrows, paraIntegr) {
  let txt = p.getText();
  // 1) Replace tabs / soft breaks / page breaks / non-breaking spaces with a single space.
  txt = txt.replace(/[\u00A0\u2007\u202F\u200B\u200C\u200D]/g, ' '); // nbsp, figure space, thin space, zero-width
  txt = txt.replace(/\t/g, ' ');
  txt = txt.replace(/\r/g, '');
  txt = txt.replace(/\u2028/g, '');  // line separator
  // 2) Replace multiple spaces with one.
  txt = txt.replace(/[ ]{2,}/g, ' ');
  if (paraIntegr) {
    // Insert pilcrow at every paragraph break.
    if (usePilcrows) {
      txt = txt.replace(/\n+/g, ' ' + PILCROW + ' ');
    } else {
      txt = txt.replace(/\n+/g, ' ');
    }
  } else {
    txt = txt.replace(/\n+/g, ' ');
  }
  txt = txt.replace(/^\s+|\s+$/g, '');
  // Only assign if it actually changed.
  if (txt !== p.getText()) p.setText(txt);
}

function condenseNoPilcrows_() { condenseCard_(false); }
function condenseWithPilcrows_() { condenseCard_(true); }

function uncondense_() {
  // Replace pilcrows with real paragraph breaks.
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let n = 0;
  for (const p of paragraphs) {
    const txt = p.getText();
    const m = txt.match(PILCROW_RE);
    if (!m) continue;
    // We must split the paragraph by pilcrows; subsequent ones become children of p.
    const parts = txt.split(PILCROW_RE);
    if (parts.length <= 1) continue;
    p.setText(parts[0].trim());
    let last = p;
    for (let i = 1; i < parts.length; i++) {
      const np = doc.getBody().insertParagraphAfter(last, parts[i].trim());
      np.setHeading(DocumentApp.ParagraphHeading.NORMAL);
      last = np;
    }
    n++;
  }
  DocumentApp.getUi().alert('Uncondensed ' + n + ' paragraph(s).');
}

// ---------- Shrink ----------

function shrinkText_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  const range = resolveScope_(doc, paragraphs, /*preferCard=*/true);
  if (!range) {
    DocumentApp.getUi().alert('Shrink: place cursor in a card or select text.');
    return;
  }
  const startIdx = paragraphs.indexOf(range.startP);
  const endIdx = paragraphs.indexOf(range.endP);
  let touched = 0;
  for (let i = startIdx; i <= endIdx; i++) {
    const p = paragraphs[i];
    if (p.getHeading() !== DocumentApp.ParagraphHeading.NORMAL) continue;
    shrinkParagraph_(p);
    touched++;
  }
  DocumentApp.getUi().alert('Shrunk ' + touched + ' card paragraph(s).');
}

function shrinkParagraph_(p) {
  // Decide target size: walk the size cycle by reading the smallest font size
  // in any un-underlined range.
  const text = p.editAsText();
  const t = text.getText();
  if (!t.length) return;
  let baseSize = text.getFontSize(0) || 11;
  // Find smallest non-pilcrow font size (Word ignores pilcrows for size decision).
  for (let i = 0; i < t.length; i++) {
    const c = t[i];
    if (PILCROW_RE.test(c)) continue;
    const s = text.getFontSize(i) || 11;
    if (s && s < baseSize) baseSize = s;
  }
  // Find the next smaller size in cycle, else wrap to base (Normal).
  const cycleIdx = SHRINK_SIZES.indexOf(baseSize);
  let newSize;
  if (cycleIdx === -1) newSize = 8;
  else if (cycleIdx === SHRINK_SIZES.length - 1) newSize = 11;
  else newSize = SHRINK_SIZES[cycleIdx + 1];
  // Apply to un-underlined runs only.
  let i = 0;
  while (i < t.length) {
    // Skip pilcrows
    if (PILCROW_RE.test(t[i])) { i++; continue; }
    // Find end of un-underlined run.
    let j = i;
    while (j < t.length && !text.isUnderline(j) && !PILCROW_RE.test(t[j])) j++;
    if (j > i) text.setFontSize(i, j - 1, newSize);
    i = j + 1;
  }
  // Restore omission note size if option says so.
  const settings = loadSettings_();
  if (!settings.shrinkOmissions) {
    const re = OMISSION_RE;
    let m;
    while ((m = re.exec(t)) !== null) {
      const start = m.index;
      const end = m.index + m[0].length - 1;
      try { text.setFontSize(start, end, 11); } catch (e) {}
    }
  }
}

function unshrinkAll_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let n = 0;
  for (const p of paragraphs) {
    if (p.getHeading() !== DocumentApp.ParagraphHeading.NORMAL) continue;
    const text = p.editAsText();
    const t = text.getText();
    let i = 0;
    while (i < t.length) {
      let j = i + 1;
      while (j < t.length && text.getFontSize(j) === text.getFontSize(i)) j++;
      if (text.getFontSize(i) < 11) {
        text.setFontSize(i, j - 1, 11);
      }
      i = j;
    }
    n++;
  }
  DocumentApp.getUi().alert('Reset font size on ' + n + ' paragraph(s).');
}

// ---------- Scope resolution ----------

function resolveScope_(doc, paragraphs, preferCard) {
  const sel = doc.getSelection();
  if (sel) {
    const elements = sel.getSelectedElements();
    if (elements && elements.length) {
      // Find paragraph indices for first and last selected paragraph.
      let startIdx = -1, endIdx = -1;
      for (const el of elements) {
        const p = el.getElement().asParagraph ? el.getElement().asParagraph() :
                  (el.getElement().getParent && el.getElement().getParent().asParagraph
                    ? el.getElement().getParent().asParagraph() : null);
        if (!p) continue;
        const idx = paragraphs.indexOf(p);
        if (idx < 0) continue;
        if (startIdx === -1) startIdx = idx;
        endIdx = idx;
      }
      if (startIdx !== -1) {
        return { startP: paragraphs[startIdx], endP: paragraphs[endIdx] };
      }
    }
  }
  // No selection: prefer the cursor's card; fall back to heading+content.
  const cursor = doc.getCursor();
  if (!cursor) return null;
  const el = cursor.getElement();
  const p = el.asParagraph ? el.asParagraph() :
            (el.getParent && el.getParent().asParagraph ? el.getParent().asParagraph() : null);
  if (!p) return null;
  if (preferCard && p.getHeading() === DocumentApp.ParagraphHeading.NORMAL) {
    return { startP: p, endP: p };
  }
  const endIdx = findHeadingEndIndex_(p);
  const startIdx = paragraphs.indexOf(p);
  return { startP: paragraphs[startIdx], endP: paragraphs[endIdx] };
}


// ========== Paperless.gs ==========

/**
 * Verbatim — paperless operations
 *
 * Send-to-speech and Mark-Card are the centerpiece of paperless debate:
 * cut a card from the open file and append it (or insert a marker) into
 * the speech document.
 *
 * We approximate the Word behavior as follows:
 *   - The active speech doc is identified by document property
 *     'VerbatimSpeechDocId' (set by the user with "Set Speech Doc" in the
 *     sidebar).  If unset, we scan open docs by title containing "Speech".
 *   - If no speech doc is open, we prompt the user to create one.
 *   - On cross-doc copy, we strip Verbatim style metadata that won't
 *     render well in a speech doc (bold/italic still preserved).
 */

function cmdSendToSpeech() { sendToSpeech_(false); }
function cmdSendToSpeechEnd() { sendToSpeech_(true); }
function cmdMarkCard() { markCardInSpeechDoc_(); }

function cmdNewDocument() { newVerbatimDocument_(false); }
function cmdNewSpeech() { newVerbatimDocument_(true); }
function cmdWordCount() { wordCount_(false); }
function cmdDocStats() { docStats_(); }

function setActiveSpeechDoc(docId) {
  PropertiesService.getDocumentProperties().setProperty('VerbatimSpeechDocId', docId);
  return { ok: true };
}

// ---------- Implementations ----------

function sendToSpeech_(atEnd) {
  const cur = DocumentApp.getActiveDocument();
  const speechDoc = resolveSpeechDoc_(cur);
  if (!speechDoc) return;
  const sel = cur.getSelection();
  const paragraphs = cur.getBody().getParagraphs();
  let targets = [];
  if (sel) {
    // Capture selected range paragraphs.
    const elements = sel.getSelectedElements();
    const seen = new Set();
    for (const el of elements) {
      const p = el.getElement().asParagraph ? el.getElement().asParagraph() :
                (el.getElement().getParent && el.getElement().getParent().asParagraph
                  ? el.getElement().getParent().asParagraph() : null);
      if (p && !seen.has(p)) { seen.add(p); targets.push(p); }
    }
    if (!targets.length) {
      DocumentApp.getUi().alert('Send To Speech: selection is empty.');
      return;
    }
  } else {
    // Cursor: use heading+content.
    const cursor = cur.getCursor();
    if (!cursor) {
      DocumentApp.getUi().alert('Send To Speech: place cursor in a card.');
      return;
    }
    const el = cursor.getElement();
    const p = el.asParagraph ? el.asParagraph() :
              (el.getParent && el.getParent().asParagraph ? el.getParent().asParagraph() : null);
    if (!p) return;
    const endIdx = findHeadingEndIndex_(p);
    const startIdx = paragraphs.indexOf(p);
    for (let i = startIdx; i <= endIdx; i++) targets.push(paragraphs[i]);
  }
  // Append to speech doc.
  const speechBody = speechDoc.getBody();
  if (atEnd) {
    speechBody.appendParagraph('');
  }
  for (const p of targets) {
    const txt = p.getText();
    const heading = p.getHeading();
    const bold = p.isBold();
    const fontSize = p.getFontSize();
    let newP;
    if (atEnd) {
      newP = speechBody.appendParagraph(txt);
    } else {
      newP = speechBody.appendParagraph(txt);
    }
    newP.setHeading(heading);
    if (bold) newP.setBold(true);
    if (fontSize) newP.setFontSize(fontSize);
  }
  DocumentApp.getUi().alert('Sent ' + targets.length + ' paragraph(s) to speech doc.');
}

function markCardInSpeechDoc_() {
  const cur = DocumentApp.getActiveDocument();
  const speechDoc = resolveSpeechDoc_(cur);
  if (!speechDoc) return;
  if (speechDoc.getId() !== cur.getId()) {
    DocumentApp.getUi().alert('Mark Card: switch to the speech doc first; cursor must be inside it.');
    return;
  }
  const marker = markedMarker(new Date());
  const body = speechDoc.getBody();
  const p = body.appendParagraph(marker);
  p.setFontSize(16);
  p.setForegroundColor('#cc0000');
  p.setBold(true);
  DocumentApp.getUi().alert('Marked at ' + marker);
}

function resolveSpeechDoc_(cur) {
  const docProps = PropertiesService.getDocumentProperties();
  let targetId = docProps.getProperty('VerbatimSpeechDocId');
  if (targetId) {
    try { return DocumentApp.openById(targetId); }
    catch (e) {
      DocumentApp.getUi().alert(
        'The configured speech doc cannot be opened. Clear the binding from the sidebar.'
      );
      return null;
    }
  }
  // Search all files in Drive for a doc containing "Speech" in the title and
  // matching this user.
  const files = DriveApp.getFilesByType(MimeType.GOOGLE_DOCS);
  const candidates = [];
  while (files.hasNext()) {
    const f = files.next();
    if (/speech/i.test(f.getName())) candidates.push(f);
  }
  if (candidates.length === 0) {
    const ui = DocumentApp.getUi();
    const resp = ui.alert(
      'No speech document found. Create one now?',
      ui.ButtonSet.OK
    );
    if (resp !== ui.Button.OK) return null;
    return newVerbatimDocument_(true);
  }
  if (candidates.length > 1) {
    const list = candidates.map((f, i) => `${i+1}. ${f.getName()}`).join('\n');
    const resp = DocumentApp.getUi().prompt(
      'Multiple speech documents found. Choose one (enter the number):\n' + list
    );
    const pick = parseInt(resp.getResponseText().trim(), 10);
    if (!pick || pick < 1 || pick > candidates.length) return null;
    targetId = candidates[pick - 1].getId();
  } else {
    targetId = candidates[0].getId();
  }
  docProps.setProperty('VerbatimSpeechDocId', targetId);
  return DocumentApp.openById(targetId);
}

function newVerbatimDocument_(asSpeech) {
  const doc = DocumentApp.create(asSpeech ? 'Speech.doc' : 'Verbatim Document.doc');
  installCanonicalStyles(doc);
  const body = doc.getBody();
  body.setText('');
  if (asSpeech) {
    // Speech docs have a simple "Tag" header at the top by convention.
    body.appendParagraph('Speech').setHeading(DocumentApp.ParagraphHeading.HEADING4);
  }
  DocumentApp.getUi().alert('Created ' + (asSpeech ? 'speech' : 'Verbatim') + ' document: ' + doc.getUrl());
  return doc;
}

function wordCount_(bySection) {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let total = 0;
  let headerCount = 0;
  for (const p of paragraphs) {
    const h = p.getHeading();
    if (h !== DocumentApp.ParagraphHeading.NORMAL) {
      headerCount += debateWordCount(p.getText());
      continue;
    }
    total += debateWordCount(p.getText());
  }
  DocumentApp.getUi().alert(
    'Word count (Verbatim style):\n' +
    '  Card text: ' + total + '\n' +
    '  Headings:  ' + headerCount + '\n' +
    '  Total:     ' + (total + headerCount)
  );
}

function docStats_() {
  const doc = DocumentApp.getActiveDocument();
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let cards = 0, tags = 0, blocks = 0, hats = 0, pockets = 0;
  for (const p of paragraphs) {
    const h = p.getHeading();
    if (h === DocumentApp.ParagraphHeading.HEADING1) pockets++;
    else if (h === DocumentApp.ParagraphHeading.HEADING2) hats++;
    else if (h === DocumentApp.ParagraphHeading.HEADING3) blocks++;
    else if (h === DocumentApp.ParagraphHeading.HEADING4) tags++;
    else cards++;
  }
  DocumentApp.getUi().alert(
    'Document stats:\n' +
    '  Pockets: ' + pockets + '\n' +
    '  Hats:    ' + hats + '\n' +
    '  Blocks:  ' + blocks + '\n' +
    '  Tags:    ' + tags + '\n' +
    '  Cards:   ' + cards
  );
}


// ========== Migrate.gs ==========

/**
 * Verbatim — Word → Google Docs conversion
 *
 * Many existing Verbatim files are .docx/.docm. When such a file is opened in
 * Google Drive, it auto-converts to a Google Doc but loses:
 *   - Some style metadata (custom Verbatim styles → mapped to "Heading 1" etc.
 *     by the importer, but custom style attributes are dropped)
 *   - Pilcrows (¶) survive as text in most cases
 *
 * This module provides:
 *   - migrateFromWord_(doc):   post-conversion pass that re-applies the
 *                               canonical Verbatim styles based on heading
 *                               level + bold state.
 *   - docxToVerbatimText_(blob): for users who paste the raw .docx text,
 *                                return a Verbatim-friendly version with
 *                                pilcrows inserted where appropriate.
 *
 * It is intentionally non-destructive: nothing is rewritten unless the
 * source had recognizable Verbatim patterns. Plain text from a PDF, for
 * example, will be left alone.
 */

function cmdMigrateFromWord() {
  const doc = DocumentApp.getActiveDocument();
  const n = migrateFromWord_(doc);
  DocumentApp.getUi().alert('Migrated ' + n + ' paragraph(s) into Verbatim styles.');
}

/**
 * Re-apply canonical styles. Returns number of paragraphs modified.
 *
 * Heuristics:
 *   - HEADING1 → Pocket
 *   - HEADING2 → Hat
 *   - HEADING3 → Block
 *   - HEADING4 → Tag
 *   - BOLD NORMAL_TEXT with lastname-pattern → Cite
 *   - HEADING paragraph that's empty → mark for cleanup
 *   - All other NORMAL_TEXT paragraphs are left as VerbatimCard.
 */
function migrateFromWord_(doc) {
  installCanonicalStyles(doc);
  const body = doc.getBody();
  const paragraphs = body.getParagraphs();
  let n = 0;
  for (const p of paragraphs) {
    const h = p.getHeading();
    let changed = false;
    switch (h) {
      case DocumentApp.ParagraphHeading.HEADING1:
        applyParagraphStyle(p, 'Pocket'); changed = true; break;
      case DocumentApp.ParagraphHeading.HEADING2:
        applyParagraphStyle(p, 'Hat'); changed = true; break;
      case DocumentApp.ParagraphHeading.HEADING3:
        applyParagraphStyle(p, 'Block'); changed = true; break;
      case DocumentApp.ParagraphHeading.HEADING4:
        applyParagraphStyle(p, 'Tag'); changed = true; break;
      default:
        if (p.isBold()) {
          // Maybe a Cite line.
          const txt = p.getText();
          if (/^[A-Z][\w'\-]+(?:\s+[A-Z][\w'\-]+){0,3}/.test(txt)) {
            applyParagraphStyle(p, 'Cite');
            changed = true;
          }
        }
    }
    if (changed) n++;
  }
  return n;
}

/**
 * Pure-text conversion: take raw text and produce a Verbatim-friendly version.
 *   - Multiple blank lines collapse to a single blank (so Navigation Pane
 *     stays clean)
 *   - Insert ¶ at paragraph breaks if paragraphIntegrity setting is on
 *   - Bold the cite-line name+date heuristically
 *
 * Useful when the user pastes plain text from a PDF or HTML article.
 */
function convertPlainTextToVerbatim_(txt, opts) {
  opts = opts || {};
  const usePilcrows = opts.usePilcrows !== false;
  const paraIntegr = opts.paragraphIntegrity !== false;

  // 1) Normalize line endings.
  txt = txt.replace(/\r\n?/g, '\n');
  // 2) Collapse runs of blank lines to single blank.
  txt = txt.replace(/\n{3,}/g, '\n\n');
  // 3) If paragraph integrity, insert pilcrows at boundaries.
  if (paraIntegr && usePilcrows) {
    txt = txt.replace(/\n+/g, ' ' + PILCROW + ' ');
  } else {
    txt = txt.replace(/\n+/g, ' ');
  }
  // 4) Collapse repeated whitespace within a line.
  txt = txt.replace(/[ \t]{2,}/g, ' ');
  // 5) Detect cite lines: lines that start with "LastName, year," etc., and
  //    return a structured response so the caller can apply bold formatting.
  return txt;
}

/**
 * Helper that detects a probable cite line and returns matched ranges so
 * the caller can apply bold formatting.
 *   Input:  "Aaron Hardy, 1-1-3000, \"Title\", https://example.com"
 *   Output: [[0, 11], [13, 21], ...]  (ranges of name + date)
 */
function findCiteRanges_(text) {
  const ranges = [];
  const m = text.match(/^([A-Z][\w'\-]+(?:\s+[A-Z][\w'\-]+){0,3})\s*(?:,\s*([\d\-\/]{1,10}))?/);
  if (m) {
    ranges.push([m.index, m.index + m[1].length - 1]);
    if (m[2]) {
      const dateIdx = text.indexOf(m[2], m.index + m[1].length);
      if (dateIdx > -1) ranges.push([dateIdx, dateIdx + m[2].length - 1]);
    }
  }
  return ranges;
}

function cmdAutoFormatSelectionAsCite() {
  const doc = DocumentApp.getActiveDocument();
  const sel = doc.getSelection();
  if (!sel) {
    DocumentApp.getUi().alert('Select a cite paragraph first.');
    return;
  }
  const elements = sel.getSelectedElements();
  let n = 0;
  for (const el of elements) {
    const p = el.getElement().asParagraph ? el.getElement().asParagraph() : null;
    if (!p) continue;
    const t = p.editAsText();
    const txt = t.getText();
    const ranges = findCiteRanges_(txt);
    for (const [s, e] of ranges) t.setBold(s, e, true);
    applyParagraphStyle(p, 'Cite');
    n++;
  }
  DocumentApp.getUi().alert('Formatted ' + n + ' cite paragraph(s).');
}


// ========== Settings.gs ==========

/**
 * Verbatim — settings & profile
 *
 * Stored in Document Properties under the "Verbatim" namespace, mirroring
 * the Word .dotm registry pattern.  Defaults match the upstream template.
 */

function getSettings() {
  return loadSettings_();
}

function setSettings(json) {
  const props = PropertiesService.getDocumentProperties();
  Object.keys(json).forEach(k => {
    props.setProperty('Verbatim.' + k, String(json[k]));
  });
  return loadSettings_();
}

function loadSettings_() {
  const props = PropertiesService.getDocumentProperties();
  return {
    usePilcrows: props.getProperty('Verbatim.usePilcrows') !== 'false', // default true
    paragraphIntegrity: props.getProperty('Verbatim.paragraphIntegrity') !== 'false', // default true
    shrinkOmissions: props.getProperty('Verbatim.shrinkOmissions') === 'true', // default false
    underlineBold: props.getProperty('Verbatim.underlineBold') === 'true', // default false
    highlightColor: props.getProperty('Verbatim.highlightColor') || '#ffff00',
    profile: loadProfile_(),
  };
}

function loadProfile_() {
  const props = PropertiesService.getUserProperties();
  return {
    name: props.getProperty('Verbatim.user.name') || '',
    school: props.getProperty('Verbatim.user.school') || '',
  };
}

function saveProfile_(name, school) {
  const props = PropertiesService.getUserProperties();
  if (name !== undefined) props.setProperty('Verbatim.user.name', name);
  if (school !== undefined) props.setProperty('Verbatim.user.school', school);
  return loadProfile_();
}


// ========== Code.gs ==========

/**
 * Verbatim for Google Docs
 * Copyright (C) 2026 Ethan Lau / paperlessdebate.com contributors
 * Licensed GPL-3.0 — see LICENSE
 *
 * Entry points and top-level plumbing.
 */

// Entry: add-on opens
function onOpen(e) {
  DocumentApp.getUi()
    .createAddonMenu()
    .addItem('Open Verbatim sidebar', 'showSidebar')
    .addItem('New Verbatim Document', 'cmdNewDocument')
    .addItem('New Speech Document', 'cmdNewSpeech')
    .addSeparator()
    .addSubMenu(DocumentApp.getUi().createMenu('Format')
          .addItem('Paste Text (F2)', 'cmdPasteText')
          .addItem('Condense (F3)', 'cmdCondense')
          .addItem('Condense No Pilcrows', 'cmdCondenseNoPilcrows')
          .addItem('Condense With Pilcrows', 'cmdCondenseWithPilcrows')
          .addItem('Uncondense', 'cmdUncondense')
          .addItem('Shrink', 'cmdShrink')
          .addItem('Unshrink All', 'cmdUnshrinkAll')
          .addItem('Highlight (F11)', 'cmdHighlight')
          .addItem('Underline (F9)', 'cmdUnderline')
          .addItem('Emphasis (F10)', 'cmdEmphasis')
          .addItem('Cite (F8)', 'cmdCite')
          .addItem('Clear Formatting (F12)', 'cmdClearFormatting')
          .addItem('Remove Blanks', 'cmdRemoveBlanks')
          .addItem('Remove Pilcrows', 'cmdRemovePilcrows')
          .addItem('Remove Hyperlinks', 'cmdRemoveHyperlinks')
          .addItem('Auto Format Cite', 'cmdAutoFormatCite')
          .addItem('Auto Number Tags', 'cmdAutoNumberTags')
          .addItem('De-Number Tags', 'cmdDeNumberTags')
          .addItem('Fix Formatting Gaps', 'cmdFixFormattingGaps')
          .addItem('Convert To Default Styles', 'cmdConvertToDefaultStyles')
          .addItem('Select Similar', 'cmdSelectSimilar'))
    .addSubMenu(DocumentApp.getUi().createMenu('Organize')
          .addItem('Pocket (F4)', 'cmdPocket')
          .addItem('Hat (F5)', 'cmdHat')
          .addItem('Block (F6)', 'cmdBlock')
          .addItem('Tag (F7)', 'cmdTag')
          .addItem('Move Up', 'cmdMoveUp')
          .addItem('Move Down', 'cmdMoveDown')
          .addItem('Move To Bottom', 'cmdMoveToBottom')
          .addItem('Select Heading', 'cmdSelectHeading')
          .addItem('Delete Heading', 'cmdDeleteHeading'))
    .addSubMenu(DocumentApp.getUi().createMenu('Paperless')
          .addItem('Send To Speech', 'cmdSendToSpeech')
          .addItem('Send To Speech End', 'cmdSendToSpeechEnd')
          .addItem('Mark Card', 'cmdMarkCard')
          .addItem('Word Count', 'cmdWordCount')
          .addItem('Document Stats', 'cmdDocStats')
          .addItem('Insert Header', 'cmdInsertHeader'))
    .addSubMenu(DocumentApp.getUi().createMenu('View')
          .addItem('Toggle Invisibility', 'cmdInvisibilityToggle')
          .addItem('Invisibility On', 'cmdInvisibilityOn')
          .addItem('Invisibility Off', 'cmdInvisibilityOff')
          .addItem('Default View', 'cmdDefaultView'))
    .addSubMenu(DocumentApp.getUi().createMenu('Help')
          .addItem('Verbatim Help', 'showHelp')
          .addItem('Cheat Sheet', 'showCheatSheet')
          .addItem('Install Styles (run once)', 'cmdInstallStyles'))
    .addSubMenu(DocumentApp.getUi().createMenu('Tools')
          .addItem('Migrate From Word', 'cmdMigrateFromWord')
          .addItem('Auto Format Cite (selection)', 'cmdAutoFormatSelectionAsCite'))
    .addToUi();
}

// Drive-homepage trigger: lets users "Make a copy" / open from Drive
function onHomepage(e) {
  const card = CardService.newCardBuilder()
    .setHeader(CardService.newCardHeader().setTitle('Verbatim for Google Docs'))
    .addSection(
      CardService.newCardSection()
        .addWidget(CardService.newTextParagraph().setText(
          'Open a Google Doc, then use Extensions → Verbatim for Google Docs → Open Verbatim sidebar.'))
        .addWidget(CardService.newTextParagraph().setText(
          'On first run, choose Extensions → Verbatim for Google Docs → Help → Install Styles (run once).'))
    ).build();
  return [card];
}

// Show the sidebar UI
function showSidebar() {
  const html = HtmlService.createHtmlOutputFromFile('Sidebar')
    .setTitle('Verbatim')
    .setWidth(320);
  DocumentApp.getUi().showSidebar(html);
}

function showHelp() {
  const html = HtmlService.createHtmlOutputFromFile('Help').setWidth(720).setHeight(640);
  DocumentApp.getUi().showModalDialog(html, 'Verbatim Help');
}

function showCheatSheet() {
  const html = HtmlService.createHtmlOutputFromFile('CheatSheet').setWidth(560).setHeight(640);
  DocumentApp.getUi().showModalDialog(html, 'Keyboard Shortcuts');
}

function cmdInstallStyles() {
  installCanonicalStyles(DocumentApp.getActiveDocument());
}

function cmdAutoFormatSelectionAsCite() {
  cmdAutoFormatCite();
}

// Stub for "default view" — Google Docs view toggles aren't scriptable,
// but we surface it for parity and offer a "Reading mode" hint.
function cmdDefaultView() {
  DocumentApp.getUi().alert(
    'Google Docs uses its own view toggles (View → Mode).\n' +
    'Verbatim\'s "Default View" (Word Draft view) maps to the Google Docs default editing view — no action needed.'
  );
}

// (No include() needed — multi-file Apps Script shares a global namespace.
//  See Styles.gs, Formatting.gs, Condense.gs, Shrink.gs, Cards.gs,
//  Paperless.gs, Speech.gs, Analytics.gs, View.gs, Settings.gs, Util.gs.)